services:
  mini-soar-app:
    build: .
    container_name: mini-soar
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    # Command to train the model
    command: /bin/sh -c "python train_model.py && streamlit run app.py --server.fileWatcherType none"
