
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_iam
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: CLN46cFtiN26WpgI
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: yoursecuredbpassword
      KC_DB_SCHEMA: public
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/hw8-realm-realm.json
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_config/import:/opt/keycloak/data/import 
    depends_on:
      - keycloak_db
    networks:
      - iam_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  keycloak_db:
    image: postgres:latest
    container_name: keycloak_postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: yoursecuredbpassword
    ports:
      - "5432:5432"
    networks:
      - iam_network

  flask_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_protected_api
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    tmpfs:
      - /var/lib/nginx:uid=1000,gid=1000,mode=1777
      - /var/log/nginx:uid=1000,gid=1000,mode=1777
      - /run:uid=1000,gid=1000,mode=1777
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      KEYCLOAK_SERVER_URL: "http://localhost:8080"
      KEYCLOAK_REALM_NAME: "hw8-realm"
      KEYCLOAK_CLIENT_ID: "flask-api-client"
      KEYCLOAK_CLIENT_SECRET: "yourflaskclientsecret"
      OIDC_CLIENT_SECRETS_PATH: "/app/client_secrets.json"
      APP_SECRET_KEY: "a_very_strong_and_random_secret_key"
    volumes:
      - ./app:/app
    depends_on:
      - keycloak
    networks:
      - iam_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


volumes:
  postgres_data:

networks:
  iam_network:
    driver: bridge