services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:15000"
    depends_on:
      - db
    networks:
      - frontend
    read_only: true
    tmpfs:
      - /var/lib/nginx:uid=1000,gid=1000,mode=1777
      - /var/log/nginx:uid=1000,gid=1000,mode=1777
      - /run:uid=1000,gid=1000,mode=1777
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

networks:
  frontend:
  backend: