services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:5000"
    depends_on:
      - db
    networks:
      - frontend
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
networks:
  frontend:
  backend:
